services:
  app:
    image: app-web:first
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:parola123@db:5432/recap?schema=public"
      NEXTAUTH_SECRET: "jfsdghjhghjsghsjdgjfhljgshdjgjfdshgjd"
      NEXTAUTH_URL: "http://localhost:3000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parola123
      POSTGRES_DB: recap
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
